### ISSUE TITLE
JWIN Right click feature not working

### ISSUE THREAD

**Issue by MwM-Bliss** [ssblur/Just-What-I-Needed-Mod#9] opened 2016-03-31 03:10 UTC
I installed JWIN mod for minecraft1.9 and have a problem using the right click harvest feature. I have it enabled in configs but it still does not work in game. Please help.

**Comment by ssblur** [comment] 2016-03-31 13:36
Alright, I am working on it, it will be fixed in the next release. I will close this issue once the problem is identified.

**Comment by ssblur** [comment] 2016-04-14 14:44
Sorry about the massive delay, school has been rather pressing. Problem has been identified, was a change in the way Forge handles interact hooks.

**Closed by ssblur** 2016-04-14 14:44 UTC
